=== chipercu/L2RocksPlatform/data/stats/option/option_data.dtd
<!ELEMENT list (option_data)*>
<!ELEMENT option_data  (for|set|skills|triggers)*>
<!ATTLIST option_data
	id CDATA #REQUIRED>

<!ELEMENT for (add|set)*>

<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>


<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== chipercu/L2RocksPlatform/data/stats/option/12700-12799.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="12700">
		<for>
			<add order="0x60" stat="p_max_mp" value="26.32" />
			<add order="0x60" stat="regMp" value="0.0852" />
		</for>
	</option_data>
	<option_data id="12701">
		<for>
			<add order="0x60" stat="p_max_mp" value="26.32" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12702">
		<for>
			<add order="0x60" stat="p_max_mp" value="26.32" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12703">
		<for>
			<add order="0x60" stat="p_max_mp" value="26.32" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12704">
		<for>
			<add order="0x60" stat="p_max_mp" value="26.32" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12705">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="p_physical_attack" value="5.536" />
		</for>
	</option_data>
	<option_data id="12706">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="p_magical_attack" value="6.464" />
		</for>
	</option_data>
	<option_data id="12707">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="regHp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12708">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="regMp" value="0.0852" />
		</for>
	</option_data>
	<option_data id="12709">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12710">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12711">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12712">
		<for>
			<add order="0x60" stat="p_max_cp" value="33.4488" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12713">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="p_magical_attack" value="6.464" />
		</for>
	</option_data>
	<option_data id="12714">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="regHp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12715">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="regMp" value="0.0852" />
		</for>
	</option_data>
	<option_data id="12716">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12717">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12718">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12719">
		<for>
			<add order="0x60" stat="p_physical_attack" value="5.536" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12720">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="regHp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12721">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="regMp" value="0.0852" />
		</for>
	</option_data>
	<option_data id="12722">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12723">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12724">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12725">
		<for>
			<add order="0x60" stat="p_magical_attack" value="6.464" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12726">
		<for>
			<add order="0x60" stat="regHp" value="0.13104" />
			<add order="0x60" stat="regMp" value="0.0852" />
		</for>
	</option_data>
	<option_data id="12727">
		<for>
			<add order="0x60" stat="regHp" value="0.13104" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12728">
		<for>
			<add order="0x60" stat="regHp" value="0.13104" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12729">
		<for>
			<add order="0x60" stat="regHp" value="0.13104" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12730">
		<for>
			<add order="0x60" stat="regHp" value="0.13104" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12731">
		<for>
			<add order="0x60" stat="regMp" value="0.0852" />
			<add order="0x60" stat="regCp" value="0.13104" />
		</for>
	</option_data>
	<option_data id="12732">
		<for>
			<add order="0x60" stat="regMp" value="0.0852" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12733">
		<for>
			<add order="0x60" stat="regMp" value="0.0852" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12734">
		<for>
			<add order="0x60" stat="regMp" value="0.0852" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12735">
		<for>
			<add order="0x60" stat="regCp" value="0.13104" />
			<add order="0x60" stat="p_avoid" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12736">
		<for>
			<add order="0x60" stat="regCp" value="0.13104" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12737">
		<for>
			<add order="0x60" stat="regCp" value="0.13104" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12738">
		<for>
			<add order="0x60" stat="p_avoid" value="0.8127" />
			<add order="0x60" stat="p_hit" value="0.8127" />
		</for>
	</option_data>
	<option_data id="12739">
		<for>
			<add order="0x60" stat="p_avoid" value="0.8127" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12740">
		<for>
			<add order="0x60" stat="p_hit" value="0.8127" />
			<add order="0x60" stat="p_critical_rate_diff" value="8.7999156" />
		</for>
	</option_data>
	<option_data id="12741">
		<for>
			<add order="0x60" stat="p_physical_defence" value="16.995" />
		</for>
	</option_data>
	<option_data id="12742">
		<for>
			<add order="0x60" stat="p_magical_defence" value="13.563" />
		</for>
	</option_data>
	<option_data id="12743">
		<for>
			<add order="0x60" stat="p_max_hp" value="42.075" />
		</for>
	</option_data>
	<option_data id="12744">
		<for>
			<add order="0x60" stat="p_max_mp" value="45.408" />
		</for>
	</option_data>
	<option_data id="12745">
		<for>
			<add order="0x60" stat="p_max_cp" value="63.5184" />
		</for>
	</option_data>
	<option_data id="12746">
		<for>
			<add order="0x60" stat="p_physical_attack" value="7.26" />
		</for>
	</option_data>
	<option_data id="12747">
		<for>
			<add order="0x60" stat="p_magical_attack" value="8.316" />
		</for>
	</option_data>
	<option_data id="12748">
		<for>
			<add order="0x60" stat="regHp" value="0.29304" />
		</for>
	</option_data>
	<option_data id="12749">
		<for>
			<add order="0x60" stat="regMp" value="0.20064" />
		</for>
	</option_data>
	<option_data id="12750">
		<for>
			<add order="0x60" stat="regCp" value="0.29304" />
		</for>
	</option_data>
	<option_data id="12751">
		<for>
			<add order="0x60" stat="p_avoid" value="1.674156" />
		</for>
	</option_data>
	<option_data id="12752">
		<for>
			<add order="0x60" stat="p_hit" value="1.674156" />
		</for>
	</option_data>
	<option_data id="12753">
		<for>
			<add order="0x60" stat="p_critical_rate_diff" value="18.127761168" />
		</for>
	</option_data>
	<option_data id="12754">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_magical_defence" value="6.576" />
		</for>
	</option_data>
	<option_data id="12755">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_max_hp" value="20.4" />
		</for>
	</option_data>
	<option_data id="12756">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_max_mp" value="22.016" />
		</for>
	</option_data>
	<option_data id="12757">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_max_cp" value="30.7968" />
		</for>
	</option_data>
	<option_data id="12758">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_physical_attack" value="3.52" />
		</for>
	</option_data>
	<option_data id="12759">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="p_magical_attack" value="4.032" />
		</for>
	</option_data>
	<option_data id="12760">
		<for>
			<add order="0x60" stat="p_physical_defence" value="8.755" />
			<add order="0x60" stat="regHp" value="0.14208" />
		</for>
	</option_data>
	<option_data id="12761">
