=== chipercu/L2RocksPlatform/data/xml/quests/quests.dtd
<!ELEMENT quests (quest)*>
<!ELEMENT quest (name|setting)*>
<!ATTLIST quest
	id CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	lang CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT setting (rate|event|item)*>
<!ELEMENT rate (#PCDATA)>
<!ATTLIST rate
	drop CDATA #IMPLIED
	reward CDATA #IMPLIED
	exp CDATA #IMPLIED
	sp CDATA #IMPLIED>
<!ELEMENT event (#PCDATA)>
<!ATTLIST event
	type CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED>

=== chipercu/L2RocksPlatform/data/xml/quests/[265] Chains of Slavery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="265" type="SOLO">
		<name lang="en" val="Chains of Slavery"/>
		<name lang="ru" val="Цепи рабства"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20004"/>	<!-- Imp -->
			<event type="MOBKILLED" val="20005"/>	<!-- Imp Elder -->
			<event type="QUEST_START" val="30357"/>	<!-- Kristin -->
			<event type="QUEST_TALK" val="30357"/>	<!-- Kristin -->
			<item id="1368"/>	<!-- Imp Shackles -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[195] Seven Sign, Secret Ritual of the Priests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="195" type="SOLO">
		<name lang="en" val="Seven Sign, Secret Ritual of the Priests"/>
		<name lang="ru" val="Семь Печатей, Тайные Знания Жрецов"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="QUEST_START" val="31001"/>	<!-- Claudia Athebaldt -->
			<event type="QUEST_TALK" val="31001"/>	<!-- Claudia Athebaldt -->
			<event type="QUEST_TALK" val="32576"/>	<!-- John -->
			<event type="QUEST_TALK" val="30289"/>	<!-- Raymond -->
			<event type="QUEST_TALK" val="32575"/>	<!-- Light of Dawn -->
			<event type="QUEST_TALK" val="32578"/>	<!-- Identity Confirm Device -->
			<event type="QUEST_TALK" val="32577"/>	<!-- Password Entry Device -->
			<event type="QUEST_TALK" val="32580"/>	<!-- bookshelf1_dawn -->
			<event type="QUEST_TALK" val="30969"/>	<!-- Iason Heine -->
			<item id="13822"/>	<!-- Guards of the Dawn Identity Card -->
			<item id="13823"/>	<!-- Emperor Shunaiman's Contract -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[10277] Mutated Kaneus - Dion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="10277" type="PARTY_ALL">
		<name lang="en" val="Mutated Kaneus - Dion"/>
		<name lang="ru" val="Мутант Канеус - Дион"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="18558"/>	<!-- Crimson Hatu Otis -->
			<event type="MOBKILLED" val="18559"/>	<!-- Seer Flouros -->
			<event type="QUEST_START" val="30071"/>	<!-- Lucas -->
			<event type="QUEST_TALK" val="30071"/>	<!-- Lucas -->
			<event type="QUEST_TALK" val="30461"/>	<!-- Mirien -->
			<item id="13832"/>	<!-- Crimson Hatu Otis' Cellular Tissue -->
			<item id="13833"/>	<!-- Seer Flouros' Cellular Tissue -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[144] Pailaka - Injured Dragon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="144" type="SOLO">
		<name lang="en" val="Pailaka - Injured Dragon"/>
		<name lang="ru" val="Пайлака - Дракон"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBGOTATTACKED" val="18660"/>	<!-- Latana -->
			<event type="MOBGOTATTACKED" val="18636"/>	<!-- Varka Silenos Footman -->
			<event type="MOBGOTATTACKED" val="18642"/>	<!-- Varka Silenos Warrior -->
			<event type="MOBGOTATTACKED" val="18646"/>	<!-- Varka Silenos Officer -->
			<event type="MOBGOTATTACKED" val="18654"/>	<!-- Varkas Commander -->
			<event type="MOBGOTATTACKED" val="18649"/>	<!-- Varka Silenos Great Magus -->
			<event type="MOBGOTATTACKED" val="18650"/>	<!-- Varka Silenos General -->
			<event type="MOBGOTATTACKED" val="18655"/>	<!-- Varkas Head Guard -->
			<event type="MOBGOTATTACKED" val="18657"/>	<!-- Prophet Guard -->
			<event type="MOBKILLED" val="18660"/>	<!-- Latana -->
			<event type="MOBKILLED" val="18635"/>	<!-- Varka Silenos Recruit -->
			<event type="MOBKILLED" val="18636"/>	<!-- Varka Silenos Footman -->
			<event type="MOBKILLED" val="18638"/>	<!-- Varka Silenos Scout -->
			<event type="MOBKILLED" val="18639"/>	<!-- Varka Silenos Hunter -->
			<event type="MOBKILLED" val="18640"/>	<!-- Varka Silenos Shaman -->
			<event type="MOBKILLED" val="18641"/>	<!-- Varka Silenos Priest -->
			<event type="MOBKILLED" val="18642"/>	<!-- Varka Silenos Warrior -->
			<event type="MOBKILLED" val="18644"/>	<!-- Varka Silenos Medium -->
			<event type="MOBKILLED" val="18645"/>	<!-- Varka Silenos Magus -->
			<event type="MOBKILLED" val="18646"/>	<!-- Varka Silenos Officer -->
			<event type="MOBKILLED" val="18648"/>	<!-- Varka Silenos Seer -->
			<event type="MOBKILLED" val="18649"/>	<!-- Varka Silenos Great Magus -->
			<event type="MOBKILLED" val="18650"/>	<!-- Varka Silenos General -->
			<event type="MOBKILLED" val="18652"/>	<!-- Varka Silenos Great Seer -->
			<event type="MOBKILLED" val="18653"/>	<!-- Varkas Elite Guard -->
			<event type="MOBKILLED" val="18654"/>	<!-- Varkas Commander -->
			<event type="MOBKILLED" val="18655"/>	<!-- Varkas Head Guard -->
			<event type="MOBKILLED" val="18656"/>	<!-- Varkas Head Magus -->
			<event type="MOBKILLED" val="18657"/>	<!-- Prophet Guard -->
			<event type="MOBKILLED" val="18658"/>	<!-- Disciple of Prophet -->
			<event type="MOBKILLED" val="18659"/>	<!-- Varkas Prophet -->
			<event type="MOBKILLED" val="18637"/>	<!-- Grazing Antelope -->
			<event type="MOBKILLED" val="18643"/>	<!-- Grazing Antelope -->
			<event type="MOBKILLED" val="18647"/>	<!-- Grazing Flava -->
			<event type="MOBKILLED" val="18651"/>	<!-- Grazing Elder Antelope -->
			<event type="QUEST_START" val="32499"/>	<!-- Ketra Orc Shaman  -->
			<event type="QUEST_TALK" val="32499"/>	<!-- Ketra Orc Shaman  -->
			<event type="QUEST_TALK" val="32502"/>	<!-- Ketra Orc Supporter -->
			<event type="QUEST_TALK" val="32509"/>	<!-- Ketra Orc Intelligence Officer -->
			<event type="QUEST_TALK" val="32512"/>	<!-- Ketra Orc Supporter -->
			<item id="13056"/>	<!-- Weapon Upgrade Stage 1 -->
			<item id="13057"/>	<!-- Weapon Upgrade Stage 2 -->
			<item id="13052"/>	<!-- Spear of Silenos -->
			<item id="13053"/>	<!-- Enhanced Spear of Silenos -->
			<item id="13054"/>	<!-- Complete Spear of Silenos -->
			<item id="13033"/>	<!-- Quick Healing Potion -->
			<item id="13032"/>	<!-- Pailaka Instant Shield -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[274] Skirmish with the Werewolves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="274" type="SOLO">
		<name lang="en" val="Skirmish with the Werewolves"/>
		<name lang="ru" val="Стычка с оборотнями"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20363"/>	<!-- Maraku Werewolf -->
			<event type="MOBKILLED" val="20364"/>	<!-- Maraku Werewolf Chieftain -->
			<event type="QUEST_START" val="30569"/>	<!-- Brukurse -->
			<event type="QUEST_TALK" val="30569"/>	<!-- Brukurse -->
			<item id="1477"/>	<!-- Maraku Werewolf Head -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[367] Electrifying Recharge!.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="367" type="SOLO">
		<name lang="en" val="Electrifying Recharge!"/>
		<name lang="ru" val="Подзарядка электричеством"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="21035"/>	<!-- Catherok -->
			<event type="QUEST_START" val="30673"/>	<!-- Lorain -->
			<event type="QUEST_TALK" val="30673"/>	<!-- Lorain -->
			<item id="5875"/>	<!-- Titan Lamp -->
			<item id="5876"/>	<!-- Titan Lamp -->
			<item id="5877"/>	<!-- Titan Lamp -->
			<item id="5878"/>	<!-- Titan Lamp -->
			<item id="5879"/>	<!-- Titan Lamp -->
			<item id="5880"/>	<!-- Broken Titan Lamp -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[691] Matras' Suspicious Request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="691" type="PARTY_ONE">
		<name lang="en" val="Matras' Suspicious Request"/>
		<name lang="ru" val="Подозрительная просьба Мэтреса"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="22363"/>	<!-- Body Destroyer -->
			<event type="MOBKILLED" val="22364"/>	<!-- Soul Dominator -->
			<event type="MOBKILLED" val="22365"/>	<!-- Labyrinth Watchman -->
			<event type="MOBKILLED" val="22366"/>	<!-- Labyrinth Watchman -->
			<event type="MOBKILLED" val="22367"/>	<!-- Labyrinth Mystic -->
			<event type="MOBKILLED" val="22368"/>	<!-- Labyrinth Captain -->
			<event type="MOBKILLED" val="22369"/>	<!-- Labyrinth Seer -->
			<event type="MOBKILLED" val="22370"/>	<!-- Passageway Captain -->
			<event type="MOBKILLED" val="22371"/>	<!-- Passageway Guards -->
			<event type="MOBKILLED" val="22372"/>	<!-- Passageway Mystic -->
			<event type="QUEST_START" val="32245"/>	<!-- Matras -->
			<event type="QUEST_TALK" val="32245"/>	<!-- Matras -->
			<item id="10372"/>	<!-- Red Stone -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[10284] Acquisition Of Divine Sword.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="10284" type="SOLO">
		<name lang="en" val="Acquisition Of Divine Sword"/>
		<name lang="ru" val="Получение чудесного меча"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="18846"/>	<!-- Kegor -->
			<event type="MOBKILLED" val="22766"/>	<!-- Mithril Millipede -->
			<event type="QUEST_START" val="32020"/>	<!-- Rafforty -->
			<event type="QUEST_TALK" val="32020"/>	<!-- Rafforty -->
			<event type="QUEST_TALK" val="32020"/>	<!-- Rafforty -->
			<event type="QUEST_TALK" val="32760"/>	<!-- Jinia  -->
			<event type="QUEST_TALK" val="32653"/>	<!-- Krun -->
			<event type="QUEST_TALK" val="32654"/>	<!-- Tarun -->
			<event type="QUEST_TALK" val="32653"/>	<!-- Krun -->
			<event type="QUEST_TALK" val="32654"/>	<!-- Tarun -->
			<event type="QUEST_TALK" val="18846"/>	<!-- Kegor -->
		</setting>
	</quest>
</quests>
