=== chipercu/L2RocksPlatform/data/xml/quests/quests.dtd
<!ELEMENT quests (quest)*>
<!ELEMENT quest (name|setting)*>
<!ATTLIST quest
	id CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	lang CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT setting (rate|event|item)*>
<!ELEMENT rate (#PCDATA)>
<!ATTLIST rate
	drop CDATA #IMPLIED
	reward CDATA #IMPLIED
	exp CDATA #IMPLIED
	sp CDATA #IMPLIED>
<!ELEMENT event (#PCDATA)>
<!ATTLIST event
	type CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED>

=== chipercu/L2RocksPlatform/data/xml/quests/[298] Lizardmen's Conspiracy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="298" type="SOLO">
		<name lang="en" val="Lizardmen's Conspiracy"/>
		<name lang="ru" val="Заговор Ящеров"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20922"/>	<!-- Maille Lizardman Warrior -->
			<event type="MOBKILLED" val="20923"/>	<!-- Maille Lizardman Shaman -->
			<event type="MOBKILLED" val="20924"/>	<!-- Maille Lizardman Matriarch -->
			<event type="MOBKILLED" val="20926"/>	<!-- Poison Araneid -->
			<event type="MOBKILLED" val="20927"/>	<!-- King of the Araneid -->
			<event type="QUEST_START" val="30333"/>	<!-- Praga -->
			<event type="QUEST_TALK" val="30333"/>	<!-- Praga -->
			<event type="QUEST_TALK" val="30333"/>	<!-- Praga -->
			<event type="QUEST_TALK" val="30344"/>	<!-- Rohmer -->
			<item id="7182"/>	<!-- Patrol's Report -->
			<item id="7183"/>	<!-- Shining Gem -->
			<item id="7184"/>	<!-- Shining Red Gem -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[464] Oath.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="464" type="SOLO">
		<name lang="en" val="Oath"/>
		<name lang="ru" val="Клятва"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="QUEST_TALK" val="32596"/>	<!-- Sophia -->
			<event type="QUEST_TALK" val="30657"/>	<!-- Seresin -->
			<event type="QUEST_TALK" val="30839"/>	<!-- Holly -->
			<event type="QUEST_TALK" val="30899"/>	<!-- Flauen -->
			<event type="QUEST_TALK" val="31350"/>	<!-- Dominic -->
			<event type="QUEST_TALK" val="30539"/>	<!-- Chichirin -->
			<event type="QUEST_TALK" val="30297"/>	<!-- Tobias -->
			<event type="QUEST_TALK" val="31960"/>	<!-- Buryun -->
			<event type="QUEST_TALK" val="31588"/>	<!-- Agnes -->
			<item id="15538"/>	<!-- Book of Silence  -->
			<item id="15539"/>	<!-- Book of Silence  -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[309] For a Good Cause.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="309" type="SOLO">
		<name lang="en" val="For a Good Cause"/>
		<name lang="ru" val="For a Good Cause"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="22650"/>	<!-- Mucrokian Fanatic -->
			<event type="MOBKILLED" val="22651"/>	<!-- Mucrokian Ascetic -->
			<event type="MOBKILLED" val="22652"/>	<!-- Mucrokian Savior -->
			<event type="MOBKILLED" val="22653"/>	<!-- Mucrokian Preacher -->
			<event type="MOBKILLED" val="22654"/>	<!-- Contaminated Mucrokian -->
			<event type="MOBKILLED" val="22655"/>	<!-- Awakened Mucrokian -->
			<event type="QUEST_START" val="32647"/>	<!-- Atra -->
			<event type="QUEST_TALK" val="32647"/>	<!-- Atra -->
			<item id="14873"/>	<!-- Mucrokian Hide -->
			<item id="14874"/>	<!-- Fallen Mucrokian Hide -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[712] Path to Becoming a Lord - Oren.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="712" type="SOLO">
		<name lang="en" val="Path to Becoming a Lord - Oren"/>
		<name lang="ru" val="Путь Лорда - Орен"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="21261"/>	<!-- Ol Mahum Transcender -->
			<event type="MOBKILLED" val="20576"/>	<!-- Oel Mahum Witch Doctor -->
			<event type="MOBKILLED" val="20575"/>	<!-- Oel Mahum Warrior -->
			<event type="MOBKILLED" val="20161"/>	<!-- Oel Mahum -->
			<event type="QUEST_START" val="35226"/>	<!-- Brasseur -->
			<event type="QUEST_START" val="30169"/>	<!-- Marty -->
			<event type="QUEST_TALK" val="35226"/>	<!-- Brasseur -->
			<event type="QUEST_TALK" val="30169"/>	<!-- Marty -->
			<event type="QUEST_TALK" val="30676"/>	<!-- Croop -->
			<event type="QUEST_TALK" val="30176"/>	<!-- Valleria -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[368] Trespassing into the Sacred Area.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="368" type="SOLO">
		<name lang="en" val="Trespassing into the Sacred Area"/>
		<name lang="ru" val="Вторжение на Святую Землю"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20794"/>	<!-- Blade Stakato -->
			<event type="MOBKILLED" val="20795"/>	<!-- Blade Stakato Worker -->
			<event type="MOBKILLED" val="20796"/>	<!-- Blade Stakato Warrior -->
			<event type="MOBKILLED" val="20797"/>	<!-- Blade Stakato Drone -->
			<event type="QUEST_START" val="30926"/>	<!-- Restina -->
			<event type="QUEST_TALK" val="30926"/>	<!-- Restina -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[324] Sweetest Venom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="324" type="SOLO">
		<name lang="en" val="Sweetest Venom"/>
		<name lang="ru" val="Сладчайший яд"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20034"/>	<!-- Prowler -->
			<event type="MOBKILLED" val="20038"/>	<!-- Venomous Spider -->
			<event type="MOBKILLED" val="20043"/>	<!-- Arachnid Tracker -->
			<event type="QUEST_START" val="30351"/>	<!-- Astaron -->
			<event type="QUEST_TALK" val="30351"/>	<!-- Astaron -->
			<item id="1077"/>	<!-- Venom Sac -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[646] Signs of Revolt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="646" type="SOLO">
		<name lang="en" val="Signs of Revolt"/>
		<name lang="ru" val="Признаки восстания"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="22691"/>	<!-- Ragna Orc -->
			<event type="MOBKILLED" val="22692"/>	<!-- Ragna Orc Warrior -->
			<event type="MOBKILLED" val="22693"/>	<!-- Ragna Orc Hero -->
			<event type="MOBKILLED" val="22694"/>	<!-- Ragna Orc Commander -->
			<event type="MOBKILLED" val="22695"/>	<!-- Ragna Orc Healer -->
			<event type="MOBKILLED" val="22696"/>	<!-- Ragna Orc Shaman -->
			<event type="MOBKILLED" val="22697"/>	<!-- Ragna Orc Seer -->
			<event type="MOBKILLED" val="22698"/>	<!-- Ragna Orc Archer -->
			<event type="MOBKILLED" val="22699"/>	<!-- Ragna Orc Sniper -->
			<event type="QUEST_START" val="32016"/>	<!-- Torrant -->
			<event type="QUEST_TALK" val="32016"/>	<!-- Torrant -->
			<item id="8087"/>	<!-- Cursed Doll -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[316] Destroy Plague Carriers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="316" type="SOLO">
		<name lang="en" val="Destroy Plague Carriers"/>
		<name lang="ru" val="Разносчики чумы"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20040"/>	<!-- Sukar Wererat -->
			<event type="MOBKILLED" val="20047"/>	<!-- Sukar Wererat Leader -->
			<event type="MOBKILLED" val="27020"/>	<!-- Varool Foulclaw -->
			<event type="QUEST_START" val="30155"/>	<!-- Ellenia -->
			<event type="QUEST_TALK" val="30155"/>	<!-- Ellenia -->
			<item id="1042"/>	<!-- Wererat's Fang -->
			<item id="1043"/>	<!-- Varool Foulclaw's Fang -->
		</setting>
	</quest>
</quests>
