=== chipercu/L2RocksPlatform/data/xml/quests/quests.dtd
<!ELEMENT quests (quest)*>
<!ELEMENT quest (name|setting)*>
<!ATTLIST quest
	id CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	lang CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT setting (rate|event|item)*>
<!ELEMENT rate (#PCDATA)>
<!ATTLIST rate
	drop CDATA #IMPLIED
	reward CDATA #IMPLIED
	exp CDATA #IMPLIED
	sp CDATA #IMPLIED>
<!ELEMENT event (#PCDATA)>
<!ATTLIST event
	type CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED>

=== chipercu/L2RocksPlatform/data/xml/quests/[159] Protect the Water Source.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="159" type="SOLO">
		<name lang="en" val="Protect the Water Source"/>
		<name lang="ru" val="Защита водного источника"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="27017"/>	<!-- Plague Zombie -->
			<event type="QUEST_START" val="30154"/>	<!-- Asterios -->
			<event type="QUEST_TALK" val="30154"/>	<!-- Asterios -->
			<item id="1035"/>	<!-- Plague Dust -->
			<item id="1071"/>	<!-- Hyacinth Charm -->
			<item id="1072"/>	<!-- Hyacinth Charm -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[198] Seven Sign, Embryo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="198" type="SOLO">
		<name lang="en" val="Seven Sign, Embryo"/>
		<name lang="ru" val="Семь Печатей, Эмбрио"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="27346"/>	<!-- Shilens Evil Thoughts -->
			<event type="QUEST_START" val="32593"/>	<!-- Wood -->
			<event type="QUEST_TALK" val="32593"/>	<!-- Wood -->
			<event type="QUEST_TALK" val="32597"/>	<!-- Franz -->
			<event type="QUEST_TALK" val="32582"/>	<!-- Jaina -->
			<item id="14360"/>	<!-- Sculpture of Doubt -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[188] Seal Removal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="188" type="SOLO">
		<name lang="en" val="Seal Removal"/>
		<name lang="ru" val="Снятие Печати"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="NPC_FIRST_TALK" val="30673"/>	<!-- Lorain -->
			<event type="QUEST_TALK" val="30970"/>	<!-- Dorothy -->
			<event type="QUEST_TALK" val="30621"/>	<!-- Nikola -->
			<event type="QUEST_TALK" val="30673"/>	<!-- Lorain -->
			<item id="10369"/>	<!-- Broken Metal Pieces -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[10502] Freya Embroidered Soul Cloak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="10502" type="PARTY_ALL">
		<name lang="en" val="Freya Embroidered Soul Cloak"/>
		<name lang="ru" val="Плащ с вышитой душой -2 (Фрея)"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="29179"/>	<!-- Freya -->
			<event type="MOBKILLED" val="29180"/>	<!-- Freya -->
			<event type="QUEST_START" val="32612"/>	<!-- Olf Adams -->
			<event type="QUEST_TALK" val="32612"/>	<!-- Olf Adams -->
			<event type="QUEST_TALK" val="32612"/>	<!-- Olf Adams -->
			<item id="21723"/>	<!-- Freya Soul Fragment -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[628] Hunt of the Golden Ram Mercenary Force.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="628" type="PARTY_ONE">
		<name lang="en" val="Hunt of the Golden Ram Mercenary Force"/>
		<name lang="ru" val="Наемники Золотого Овна"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="21508"/>	<!-- Splinter Stakato -->
			<event type="MOBKILLED" val="21509"/>	<!-- Splinter Stakato Worker -->
			<event type="MOBKILLED" val="21510"/>	<!-- Splinter Stakato Soldier -->
			<event type="MOBKILLED" val="21511"/>	<!-- Splinter Stakato Drone -->
			<event type="MOBKILLED" val="21512"/>	<!-- Splinter Stakato Drone -->
			<event type="MOBKILLED" val="21513"/>	<!-- Needle Stakato -->
			<event type="MOBKILLED" val="21514"/>	<!-- Needle Stakato Worker -->
			<event type="MOBKILLED" val="21515"/>	<!-- Needle Stakato Soldier -->
			<event type="MOBKILLED" val="21516"/>	<!-- Needle Stakato Drone -->
			<event type="MOBKILLED" val="21517"/>	<!-- Needle Stakato Drone -->
			<event type="MOBKILLED" val="21518"/>	<!-- Frenzy Stakato Soldier -->
			<event type="QUEST_START" val="31554"/>	<!-- Kahman -->
			<event type="QUEST_TALK" val="31554"/>	<!-- Kahman -->
			<item id="7248"/>	<!-- Splinter Stakato Chitin -->
			<item id="7249"/>	<!-- Needle Stakato Chitin -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[35] Find Glittering Jewelry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="35" type="SOLO">
		<name lang="en" val="Find Glittering Jewelry"/>
		<name lang="ru" val="Свадебные украшения"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="20135"/>	<!-- Alligator -->
			<event type="QUEST_START" val="30091"/>	<!-- Ellie -->
			<event type="QUEST_TALK" val="30091"/>	<!-- Ellie -->
			<event type="QUEST_TALK" val="30091"/>	<!-- Ellie -->
			<event type="QUEST_TALK" val="30879"/>	<!-- Felton -->
			<item id="7162"/>	<!-- Rough Jewel -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[308] Reed Field Maintenance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="308" type="SOLO">
		<name lang="en" val="Reed Field Maintenance"/>
		<name lang="ru" val="Reed Field Maintenance"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="MOBKILLED" val="22650"/>	<!-- Mucrokian Fanatic -->
			<event type="MOBKILLED" val="22651"/>	<!-- Mucrokian Ascetic -->
			<event type="MOBKILLED" val="22652"/>	<!-- Mucrokian Savior -->
			<event type="MOBKILLED" val="22653"/>	<!-- Mucrokian Preacher -->
			<event type="MOBKILLED" val="22654"/>	<!-- Contaminated Mucrokian -->
			<event type="MOBKILLED" val="22655"/>	<!-- Awakened Mucrokian -->
			<event type="QUEST_START" val="32646"/>	<!-- Katensa -->
			<event type="QUEST_TALK" val="32646"/>	<!-- Katensa -->
			<item id="14871"/>	<!-- Mucrokian Hide -->
			<item id="14872"/>	<!-- Awakened Mucrokian Hide -->
		</setting>
	</quest>
</quests>

=== chipercu/L2RocksPlatform/data/xml/quests/[174] Supply Check.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests SYSTEM "quests.dtd">

<!-- Author: L2CCCP, Date: 01.11.2015, Time: 18:10 -->
<!-- Site: http://l2cccp.com/ -->
<quests>
	<quest id="174" type="SOLO">
		<name lang="en" val="Supply Check"/>
		<name lang="ru" val="Проверка снабжения"/>
		<setting>
			<rate drop="1.0" reward="1.0" exp="1.0" sp="1.0"/>
			<event type="QUEST_START" val="32173"/>	<!-- Marcela -->
			<event type="QUEST_TALK" val="32173"/>	<!-- Marcela -->
			<event type="QUEST_TALK" val="32170"/>	<!-- Benis -->
			<event type="QUEST_TALK" val="32167"/>	<!-- Nika -->
			<item id="9792"/>	<!-- Warehouse Manifest -->
			<item id="9793"/>	<!-- Grocery Store Manifest -->
		</setting>
	</quest>
</quests>
